image: maven:latest
variables:
  MAVEN_BUILD: "mvn clean compile"
  MAVEN_TEST: "mvn test"

stages:
  - build
  - test

build:
  stage: build
  tags:
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - cd A1
    - $MAVEN_BUILD

test:
  stage: test
  tags:
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - cd A1
    - mvn verify
  artifacts:
    when: always
    reports:
      junit: 
        - target/surefire-reports/TEST-*.xml

