image: java:8
variables:
  MAVEN_BUILD: "mvnw clean compile"
  MAVEN_TEST: "mvnw test"

stages:
  - build
  - test

build:
  stage: build
  tags:
    - grad
  script:
    - cd A1
    - $MAVEN_BUILD

test:
  stage: test
  tags:
    - grad
  script:
    - cd A1
    - $MAVEN_TEST
