image: maven:latest
variables:
  MAVEN_BUILD: "./mvn clean compile"
  MAVEN_TEST: "./mvn test"

stages:
  - build
  - test

build:
  stage: build
  tags:
    - grad
  script:
    - $MAVEN_BUILD

test:
  stage: test
  tags:
    - grad
  script:
    - $MAVEN_TEST
